enable-rest-security: true

server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          driver_class: org.postgresql.Driver
  datasource:
    username: MarkedOne
    password: GuysIcaughtAnOlive
    url: jdbc:postgresql://localhost:5432/library
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

security:
  secret: Jnk3KjBj4iHg5kLP5$7VFR9l


